### ISSUE TITLE
Handle multiple attributes of same name

### ISSUE THREAD

**Issue by baumanno** [Paneon/php-vue-to-twig#14]
A node can have bound and normal attributes:

```
<div :class="`${isMobile ? 'small-6' : ''}`" class="product product-tile-wrapper">
```
The compiler should not overwrite one of these, but rather append all properties of the same name when building the replacement string.

**Comment by Macavity** [comment]
Oh god you are right.. :|

**Comment by Macavity** [comment]
Was fixed in https://github.com/Paneon/php-vue-to-twig/commit/2b5985861e999d8d635e0cd91e1b98c923b6a338
